#!/bin/bash

# Declare Functions
function sync {
# Put From Othello to Cyberlady
echo "Alright Othello, lets do this!"
	rsync -avr --progress /home/bmoore/Dump cyberlady:/home/bmoore/
	rsync -avr --progress /home/bmoore/Pictures cyberlady:/home/bmoore/
	rsync -avr --progress /home/bmoore/Plugins cyberlady:/home/bmoore/
}

function purge { 
# Purge on Othello
echo "Alright Othello, Kill Em Dead!"
	rm -rf /home/bmoore/Dump/*
	rm -rf /home/bmoore/Pictures/Screenshots/*
}


#Should we try this with options??

if [[ $1 == -s* ]]; then
	sync
elif [[ $1 == -p* ]]; then 
	purge
fi
