#!/bin/bash

# Declare Functions
function sync {
# Put From Othello to Cyberlady
if [ '$hostname = othello' ]; then
	echo "Alright Othello, lets do this!"
	#rsync -avr --progress /home/bmoore/Scripts cyberlady:/home/bmoore/
	rsync -avr --progress /home/bmoore/Dump cyberlady:/home/bmoore/
	rsync -avr --progress /home/bmoore/Pictures cyberlady:/home/bmoore/
	rsync -avr --progress /home/bmoore/Plugins cyberlady:/home/bmoore/

# Get from Othello to Cyberlady
#elif [ '$hostname = cyberlady' ]; then
#	echo "Alright Cyberlady, lets do this!"
#	#rsync -avr --progress othello:/home/bmoore/Scripts /home/bmoore/
#	rsync -avr --progress othello:/home/bmoore/Dump /home/bmoore/
#	rsync -avr --progress othello:/home/bmoore/Pictures /home/bmoore/
fi
}

function purge { 
# Purge on Othello
if [ '$hostname = othello' ]; then
	echo "Alright Othello, Kill Em Dead!"
	rm -r /home/bmoore/Dump/*
	rm -r /home/bmoore/Pictures/Screenshots/*
	
# Purge Cyberlady
#elif [ '$hostname = cyberlady' ]; then
#	echo "Alright Cyberlady, Kill Em Dead!"
#	rm -r /home/bmoore/Dump/*
#	rm -r /home/bmoore/Pictures/Screenshots/*
fi
}


#Should we try this with options??

if [[ $1 == -s* ]]; then
	sync
elif [[ $1 == -p* ]]; then 
	purge
fi
