#!/bin/bash -x
# Set the working directory
matchdir="/home/bmoore/gibson/"
cd $matchdir

#ENGLISH
wget -r -l1 --no-parent -A.html http://www.gibsonins.com/client/osha/training/test/English/
wget -r -l1 --no-parent -A.html http://www.gibsonins.com/client/osha/training/test/English/HazardCommunication/
wget -r -l1 --no-parent -A.html http://www.gibsonins.com/client/osha/training/test/English/LOTO/
wget -r -l1 --no-parent -A.html http://www.gibsonins.com/client/osha/training/test/English/EAP/
wget -r -l1 --no-parent -A.html http://www.gibsonins.com/client/osha/training/test/English/BBP/
wget -r -l1 --no-parent -A.html http://www.gibsonins.com/client/osha/training/test/English/PPE/
wget -r -l1 --no-parent -A.html http://www.gibsonins.com/client/osha/training/test/English/Ladder/
wget -r -l1 --no-parent -A.html http://www.gibsonins.com/client/osha/training/test/English/HearingConservation/
wget -r -l1 --no-parent -A.html http://www.gibsonins.com/client/osha/training/test/English/Excavate/
wget -r -l1 --no-parent -A.html http://www.gibsonins.com/client/osha/training/test/English/Fall/
wget -r -l1 --no-parent -A.html http://www.gibsonins.com/client/osha/training/test/English/Scaffold/

# SPANISH
wget -r -l1 --no-parent -A.html http://www.gibsonins.com/client/osha/training/test/Espanol/
wget -r -l1 --no-parent -A.html http://www.gibsonins.com/client/osha/training/test/Espanol/HazardCommunication/
wget -r -l1 --no-parent -A.html http://www.gibsonins.com/client/osha/training/test/Espanol/LOTO/
wget -r -l1 --no-parent -A.html http://www.gibsonins.com/client/osha/training/test/Espanol/EAP/
wget -r -l1 --no-parent -A.html http://www.gibsonins.com/client/osha/training/test/Espanol/BBP/
wget -r -l1 --no-parent -A.html http://www.gibsonins.com/client/osha/training/test/Espanol/PPE/
wget -r -l1 --no-parent -A.html http://www.gibsonins.com/client/osha/training/test/Espanol/Ladder/
wget -r -l1 --no-parent -A.html http://www.gibsonins.com/client/osha/training/test/Espanol/HearingConservation/
wget -r -l1 --no-parent -A.html http://www.gibsonins.com/client/osha/training/test/Espanol/Excavate/
wget -r -l1 --no-parent -A.html http://www.gibsonins.com/client/osha/training/test/Espanol/Fall/
wget -r -l1 --no-parent -A.html http://www.gibsonins.com/client/osha/training/test/Espanol/Scaffold/

exit