#!/bin/bash

#Author: BMO
#Version: 1

#Start Synergy
function syn-start { 
if [[ $(hostname) = cyberlady ]]; then
	sudo tlp start
	synergyc -f othello &
elif [[ $(hostname) = othello ]]; then
	synergys -a 10.10.64.16 &
fi
}

#Kill Synergy
function syn-kill {
if [[ $(hostname) = cyberlady ]]; then
	sudo tlp start
	pkill synergyc
elif [[ $(hostname) = othello ]]; then
	pkill synergys
fi
}

#Kill and then Start Synergy
function syn-restart {
if [[ $(hostname) = cyberlady ]]; then
	pkill synergyc
	synergyc -f othello &
elif [[ $(hostname) = othello ]]; then
	pkill synergys
	synergys -a 10.10.64.16 &
fi
}

#Run it
if [[ $1 = -s* ]]; then
	syn-start
	echo -e "\nBooted!!\n"
	exit 0
elif [[ $1 = -k* ]]; then
	syn-kill
	echo -e "\nKilled It!\n"
	exit 0
elif [[ $1 = -r* ]]; then
	syn-restart
	echo -e "\nAll Done, and restarted\n"
	exit 0
fi
