#!/bin/bash

#Author: BMO
#Version: 1

#Start Synergy
function syn-start { 
	synergys -a 10.10.64.16 &
}

#Kill Synergy
function syn-kill {
	pkill synergys
}

#Kill and then Start Synergy
function syn-restart {
	pkill synergys
	synergys -a 10.10.64.16 &
}

#Run it
if [[ $1 = -s* ]]; then
	syn-start
	echo -e "\nBooted!!\n"
	exit 0
elif [[ $1 = -k* ]]; then
	syn-kill
	echo -e "\nKilled It!\n"
	exit 0
elif [[ $1 = -r* ]]; then
	syn-restart
	echo -e "\nAll Done, and restarted\n"
	exit 0
fi