#!/bin/bash


# show load that was 1.5x the number of processer cores.
# Usage l2 hiload account DD
function hiload { 
echo -e "\n\nDescription: Show times when load was over 1.5x the number of processor cores for this server."
day=$two
br="++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo -e "\n"$br"\nWhere I am: "$HOSTNAME" - "$PWD"\n"
ssh -tq bmoore_@$account.wpengine.com "sar -q -f /var/log/sysstat/sa$day | awk -vcpu=$(grep ^processor /proc/cpuinfo | wc -l) '{if ($5 > (1.5 * cpu)) print}' && exit ; bash"
echo -e $br"\n"
}
account=$1
two=$2
hiload