#!/bin/bash

while [[ -z $1 ]]; do
		echo "Login"
		echo "Get File"
		echo "Put File"
		echo "Config"
		echo -n "What would you like to do? "
		read action
## Dynamic Actions
	if	[[ $action = c* ]]; then
		echo "Alright, let's get the Config File!"
		echo -n "What is the Account Name? "
		read account
			scp root@$account.wpengine.com:/nas/wp/conf/lb/sites/$account.conf $account.conf
			nano $account.conf
		exit
	elif [[ $action != c* ]]; then
		echo -n "First, is this for Staging or for Production? "
		read envir
			if [[ $action = l* ]] && [[ $envir = p* ]]; then
				echo "Alright, logging into the Production Server"
				echo -n "What is the Account Name? "
				read account
					ssh -t root@$account.wpengine.com "cd /nas/wp/www/sites/$account ; bash"
				exit
			elif [[ $action = l* ]] && [[ $envir = s* ]]; then
				echo "Alright, logging into the Staging Server"
				echo -n "What is the Account Name? "
				read account
					ssh -t root@$account.wpengine.com "cd /nas/wp/www/staging/$account ; bash"
				exit
			elif [[ $action = g* ]] && [[ $envir = p* ]]; then
				echo "Getting the file from the Production Server"
				echo -n "What is the Account Name? "
				read account
				echo -n "Path to file? "
				read dir
				echo -n "Where do you want it local? "
				read file
					scp root@$account.wpengine.com:/nas/wp/www/sites/$account/$dir $file
				exit
			elif [[ $action = g* ]] && [[ $envir = s* ]]; then
				echo "Getting the file from the Staging Server"
				echo -n "What is the Account Name? "
				read account
				echo -n "Path to file? "
				read dir
				echo -n "Where do you want it local? "
				read file
					scp root@$account.wpengine.com:/nas/wp/www/staging/$account/$dir $file
				exit
			elif [[ $action = p* ]] && [[ $envir = p* ]]; then
				echo "Putting the File on the Production Server"
				echo -n "What is the Account Name? "
				read account
				echo -n "Where is the file named? "
				read file
				echo -n "Where do you want it on the server? "
				read dir
					scp $file root@$account.wpengine.com:/nas/wp/www/sites/$account/$dir
				exit
			elif [[ $action = p* ]] && [[ $envir = s* ]]; then
				echo "Putting the File on the Staging Server"
				echo -n "What is the Account Name? "
				read account
				echo -n "What is the file named? "
				read file
				echo -n "Where do you want it on the server? "
				read dir
					scp $file root@$account.wpengine.com:/nas/wp/www/staging/$account/$dir
				exit
			fi
	fi
done
## If Args are static
	if [[ $1 = -c ]]; then
		echo -n "What is the Account Name? "
		read account
			scp root@$account.wpengine.com:/nas/wp/conf/lb/sites/$account.conf $account.conf
			nano $account.conf
		exit
	elif [[ -z $2 ]]; then
		echo "You are missing some Args! Try again"
		exit
	elif [[ $1 = -l ]] && [[ $2 = -p ]]; then
		echo -n "What is the Account Name? "
		read account
			ssh -t root@$account.wpengine.com "cd /nas/wp/www/sites/$account ; bash"
		exit
	elif [[ $1 = -l ]] && [[ $2 = -s ]]; then
		echo -n "What is the Account Name? "
		read account
			ssh -t root@$account.wpengine.com "cd /nas/wp/www/staging/$account ; bash"
		exit
	elif [[ $1 = -get ]] && [[ $2 = -p ]]; then
		echo -n "What is the Account Name? "
		read account
		echo -n "Path to file? \c"
		read dir
		echo -n "Where do you want it local? "
		read file
			scp root@$account.wpengine.com:/nas/wp/www/sites/$account/$dir $file
		exit
	elif [[ $1 = -get ]] && [[ $2 = -s ]]; then
		echo -n "What is the Account Name? "
		read account
		echo -n "Path to file? \c"
		read dir
		echo -n "Where do you want it local? "
		read file
			scp root@$account.wpengine.com:/nas/wp/www/staging/$account/$dir $file
		exit
	elif [[ $1 = -put ]] && [[ $2 = -p ]]; then
		echo -n "What is the Account Name? "
		read account
		echo -n "Where is the file named? "
		read file
		echo -n "Where do you want it on the server? "
		read dir
			scp $file root@$account.wpengine.com:/nas/wp/www/sites/$account/$dir
		exit
	elif [[ $1 = -put ]] && [[ $2 = -s ]]; then
		echo -n "What is the Account Name? "
		read account
		echo -n "What is the file named? "
		read file
		echo -n "Where do you want it on the server? "
		read dir
			scp $file root@$account.wpengine.com:/nas/wp/www/staging/$account/$dir
		exit
	fi