#!/bin/sh

#s="sta"
#p="p*"

if [ -z $3 ]; then
			`scp root@$1.wpengine.com:/nas/wp/www/sites/$1/$2 $2`
			echo I got the file from Production!!
elif [ -n $3 ]; then 
			`scp root@$1.wpengine.com:/nas/wp/www/staging/$1/$2 $2`
			echo I got the file from staging!!
fi